---

- name: Creates directory for groovy scripts within Jenkins folder
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins

- name: copy file to remote jenkins folder
  copy:
    src: roles/jenkins_security_setup/security/jenkins.install.UpgradeWizard.state
    dest: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    mode: u=rw,g=r,o=r

- name: copy groovy script to remote. This creates admin account (admin,admin)
  copy:
    src: roles/jenkins_security_setup/security/basic-security.groovy
    dest: /var/lib/jenkins/init.groovy.d
    owner: jenkins
    group: jenkins
    mode: u=rw,g=r,o=r

- name: start jenkins
  service:
    name: jenkins
    state: restarted

# - name: sleep for 35 seconds and continue with play
#   wait_for: timeout=35
  
# - name: delete .groovy script from init folder
#   file: path=/var/lib/jenkins/init.groovy.d/basic-security.groovy state=absent


